
  
services:
  python-app:
    platform: linux/amd64
    image: python-app
    build:
      context: .
    ports:
      - "8000:5000"
    volumes:
      - python_data:/var/lib/pythondata



volumes:
  python_data: {}
